image: python

cache:
  paths:
    - server/env/

before_script:
  - python --version
  - pip install virtualenv
  - cd server/
  - python -m venv env
  - source env/bin/activate
  - pip install -r requirements.txt

test-server:
  stage: test
  script:
    - pytest --cov app tests/
