export default {
    AXIOS_GET: "AXIOS_GET",
    AXIOS_GET_SUCCESS: "AXIOS_GET_SUCCESS",
    AXIOS_GET_ERROR: "AXIOS_GET_ERROR",

    AXIOS_POST: "AXIOS_POST",
    AXIOS_POST_SUCCESS: "AXIOS_POST_SUCCESS",
    AXIOS_POST_ERROR: "AXIOS_POST_ERROR",


}
