"""
This module defines the different component types.
"""

# Store all type ID in cache instead of here.

IMAGE_MEDIA_ID = 1
VIDEO_MEDIA_ID = 2

TEXT_QUESTION_ID = 1
PRACTICAL_QUESTION_ID = 2
MULTIPLE_QUESTION_ID = 3
SINGLE_QUESTION_ID = 4

TEAM_VIEW_ID = 1
JUDGE_VIEW_ID = 2
AUDIENCE_VIEW_ID = 3
OPERATOR_VIEW_ID = 4

ADMIN_ROLE_ID = 1
EDITOR_ROLE_ID = 2

TEXT_COMPONENT_ID = 1
IMAGE_COMPONENT_ID = 2
QUESTION_COMPONENT_ID = 3
